version: '3.7'

services:
  testtemplate4.migrations:
    # image: ${DOCKER_REGISTRY-}testtemplate4sql
    env_file: .env
    build:
      context: .
      dockerfile: src/TestTemplate4.Migrations/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"